# AGPM Manifest
# This file defines your Claude Code resource dependencies

[sources]
# Add your Git repository sources here
# Example: official = "https://github.com/aig787/agpm-community.git"

# Project-specific template variables (optional)
# Provides context to AI agents - use any structure you want!
# [project]
# style_guide = "docs/STYLE_GUIDE.md"
# max_line_length = 100
# test_framework = "pytest"
#
# [project.paths]
# architecture = "docs/ARCHITECTURE.md"
# conventions = "docs/CONVENTIONS.md"
#
# Access in templates: {{ agpm.project.style_guide }}

# Tool type configurations (multi-tool support)
[tools.claude-code]
path = ".claude"
resources = { agents = { path = "agents", flatten = true }, snippets = { path = "snippets" }, commands = { path = "commands", flatten = true }, scripts = { path = "scripts" }, hooks = { merge-target = ".claude/settings.local.json" }, mcp-servers = { merge-target = ".mcp.json" } }
# Note: hooks and mcp-servers merge into configuration files (no file installation)

[tools.opencode]
path = ".opencode"
enabled = true
resources = { agents = { path = "agent", flatten = true }, commands = { path = "command", flatten = true }, mcp-servers = { merge-target = ".opencode/opencode.json" } }
# Note: MCP servers merge into opencode.json (no file installation)

[tools.agpm]
path = ".agpm"
resources = { snippets = { path = "snippets" } }

[agents]
# Add your agent dependencies here
# Example: my-agent = { source = "official", path = "agents/my-agent.md", version = "v1.0.0" }
# For OpenCode: my-agent = { source = "official", path = "agents/my-agent.md", version = "v1.0.0", tool = "opencode" }

[snippets]
# Add your snippet dependencies here
# Example: utils = { source = "official", path = "snippets/utils.md", tool = "agpm" }

[commands]
# Add your command dependencies here
import = { path = "private/claude-code/commands/import.md" }
examples = { path = "private/claude-code/commands/update-examples.md" }
commit = { path = "claude-code/commands/commit.md" }
opencode-import = { path = "private/opencode/commands/import.md", tool = "opencode" }
opencode-examples = { path = "private/opencode/commands/update-examples.md", tool = "opencode" }
opencode-commit = { path = "opencode/commands/commit.md", tool = "opencode" }

[scripts]
# Add your script dependencies here
# Example: build = { source = "official", path = "scripts/build.sh" }

[hooks]
# Add your hook dependencies here
# Example: pre-commit = { source = "official", path = "hooks/pre-commit.json" }

[mcp-servers]
# Add your MCP server dependencies here
# Example: filesystem = { source = "official", path = "mcp-servers/filesystem.json" }
